#
# COPYRIGHT 2014 Pluribus Networks Inc.
#
# All rights reserved. This copyright notice is Copyright Management
# Information under 17 USC 1202 and is included to protect this work and
# deter copyright infringement.  Removal or alteration of this Copyright
# Management Information without the express written permission from
# Pluribus Networks Inc is prohibited, and any such unauthorized removal
# or alteration will be a violation of federal law.

#MAKEVARS = CW_NO_SHADOW=true __GNUC=

include $(SRC)/Makefile.master
$(BUILD64)SUBDIRS +=	$(MACH64)
include ../../../Makefile.subdirs
